/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "I2C_MPU6050.h"
#include "I2C_MPU6050_I2C.h"
#include "I2C_MPU6050_PINS.h"
#include "I2C_MPU6050_I2C_PVT.h"
#include "I2C_MPU6050_PVT.h"
#include "I2C_MPU6050_BOOT.h"
#include "LedServiceDiscoveryStatus.h"
#include "LedServiceDiscoveryStatus_aliases.h"
#include "LedConnectedStatus.h"
#include "LedConnectedStatus_aliases.h"
#include "LedScanningStatus.h"
#include "LedScanningStatus_aliases.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "I2C_MPU6050_SCBCLK.h"
#include "I2C_MPU6050_sda.h"
#include "I2C_MPU6050_sda_aliases.h"
#include "I2C_MPU6050_scl.h"
#include "I2C_MPU6050_scl_aliases.h"
#include "I2C_MPU6050_SCB_IRQ.h"
#include "BLE_bless_isr.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

